### ISSUE TITLE
Proxying from http port

### ISSUE THREAD

**Issue by tux-tn** [ubidzz/SSL-plugin-for-engintron-BETA#2]
Hello,

I see that you are proxying content to apache ssl and adding corresponding changes to engintron. 
May be you can keep proxying to the apache http port like the default engintron config, one the one hand nginx won't need to do a ssl negociation with apache (little performance gain) and on the other hand it will reduce changes to engintron.

I will give a try to your script, even if i am using a different config in my server with 2 shared ips where one is with nginx listening to port 443 and the other apache. I made changes to apache's EA4 main template to change apache's binding port if the vhost is in the shared ip powered by nginx.

**Comment by ubidzz** [comment]
it wont matter if you are using shared IPs because on my server i  have SSL on shared IPs and they work. I did forgot to add 1 page that is needed lastnight.

I just tried engintron 1.8 and had problems and broke all my website so i am right now stripping out 1.8 new file for ssl and just using my script to handle all the SSL sites because it works with no problems.
